name: Build
'on':
  workflow_dispatch: {
    }
  push:
    branches-ignore:
    - develop
    paths-ignore:
    - '**/.md'
  pull_request:
    paths-ignore:
    - '**/.md'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Setup Java
      uses: actions/setup-java@v5.0.0
      with:
        java-version: '21'
        distribution: adopt
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.4.2
    - name: Build
      run: ./gradlew check --info
      shell: bash
    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v5.6.2
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_annotations: 'true'
        update_check: 'true'
    - name: Release (if required)
      id: get-version
      if: github.ref == 'refs/heads/main'
      run: |-
        # some script content goes here!
        echo "Version did not change on this commit. Ignoring"
        echo "tag-created=false" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
      shell: bash
    - name: Repository Dispatch
      if: (github.ref == 'refs/heads/main' && steps.get-version.outputs.tag-created
        == 'true')
      run: |-
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"release","client_payload":{"tag":"${{ steps.get-version.outputs.tag }}"}}'
      env:
        GH_TOKEN: ${{ secrets.WORKFLOWS_TOKEN }}
      shell: bash